name: 'Terraform'
on:
  pull_request:
    paths:
      - '*.tf'
  push:
    branches:
      - master
      - main

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        env:
          AWS_DEFAULT_REGION: us-east-1
